### ISSUE TITLE
Investigate High Frequency Recoil Issues

### ISSUE THREAD

**Issue by NotDanny** [VeniceUnleashed/VeniceUnleashed#96]
It doesn't feel like the vanilla game at all. Some people says that it feels like early BF3 days.
I don't know if it has anything to do with the updated rate, but it does feel weird for me.

EDIT: I've noticed that it only happens on high frequency servers

**Comment by OrfeasZ** [comment]
https://www.youtube.com/watch?v=1DA7KVCbakA&feature=youtu.be

**Comment by OrfeasZ** [comment]
This issue has been resolved in build 8456.

**Comment by kiwidoggie** [comment]
https://www.youtube.com/watch?v=rXIKyCDjUXg

Confirmed myself.
Many other weapons as the M60 also have issues with recoil. Will need to re-investigate.

**Comment by FlashHit** [comment]
Not able to reproduce this. Got fixed already I guess.
Probably fixed in 14182

**Comment by FlashHit** [comment]
This is still an issue. Not noticable with M16A3. But with AEK it's noticable.
